version: 2.1
orbs:
  node: circleci/node@1.1.6
  slack: circleci/slack@x.y.z
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
        steps:
          - run: npm install
          - run: npm test
          - run: sudo apt-get update && sudo apt-get install -y python-dev
          - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
          - run: sudo python get-pip.py
          - run: sudo pip install awscli --upgrade
          - run: aws --version
          - run: aws s3 ls
          - run: cp .env.prod .env
          - run: ls -a
          - run: npm run deploy
          #  https://circleci.com/orbs/registry/orb/circleci/slack
          - slack/notify:
              webhook: ${SLACK_WEBHOOK}
              success_message: 🎉 A $CIRCLE_JOB job has succeeded!
              failure_message: 🔴 A $CIRCLE_JOB job has failed!
              only_for_branches: master
              channel: deploy
              color: '#42e2f4'
              message: This is a custom message notification
workflows:
  build-and-test:
    jobs:
      - build-and-test
